global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "wine_quality_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9092"]

  - job_name: "wine_quality_api"
    static_configs:
      - targets: ["localhost:8000"]
    
  - job_name: "wine_quality_exporter"
    static_configs:
      - targets: ["localhost:9092"]
    
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]